language: node_js
node_js:
  - 12
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
